services:
  putio-get:
    image: jokneemo/putio-get:latest
    restart: unless-stopped
    tty: true
    secrets:
      - putio-token
    volumes:
      - ./my-media-nas:/target
    environment:
      # See README for more options
      PUTIO_OAUTH_TOKEN_FILE: /run/secrets/putio-token
      PUTIO_SYNC_ACTION: move
      PUTIO_EMPTY_TRASH: true
      PUTIO_DIRECTORY_MAP: "/Videos:/Videos,/Comics:/Literature/Comics"
      PUTIO_GUESSIT: true

secrets:
  putio-token:
    file: ./secrets/putio-token
